#!/bin/bash

set -e

CONTRIB="$(dirname "$(readlink -e "$0")")"
ROOT_FOLDER="$CONTRIB"/..
PACKAGES="$ROOT_FOLDER"/packages/
LOCALE="$ROOT_FOLDER"/electrum_trc/locale/

if [ ! -d "$LOCALE" ]; then
  echo "Run make_locale first!"
  exit 1
fi

if [ ! -d "$PACKAGES" ]; then
  echo "Run make_packages first!"
  exit 1
fi

pushd ./electrum_trc/gui/kivy/
make theming
make release
# Fix for case insensitive filesystems
if [ ! -f ../../../.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build/python ]; then
  mv ../../../.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build/Python ../../../.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build/Python.dir
  mv ../../../.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build/python.exe ../../../.buildozer/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build/python
  make release
fi
popd
