#!/bin/bash

VERSION_STRING=(`grep ELECTRUM_VERSION electrum_trc/version.py`)
TERRACOIN_ELECTRUM_VERSION=${VERSION_STRING[2]}
TERRACOIN_ELECTRUM_VERSION=${TERRACOIN_ELECTRUM_VERSION#\'}
TERRACOIN_ELECTRUM_VERSION=${TERRACOIN_ELECTRUM_VERSION%\'}
export TERRACOIN_ELECTRUM_VERSION

APK_VERSION_STRING=(`grep APK_VERSION electrum_trc/version.py`)
TERRACOIN_ELECTRUM_APK_VERSION=${APK_VERSION_STRING[2]}
TERRACOIN_ELECTRUM_APK_VERSION=${TERRACOIN_ELECTRUM_APK_VERSION#\'}
TERRACOIN_ELECTRUM_APK_VERSION=${TERRACOIN_ELECTRUM_APK_VERSION%\'}
export TERRACOIN_ELECTRUM_APK_VERSION
